version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: studsluzba
      MYSQL_USER: matija
      MYSQL_PASSWORD: Test123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: studsluzba_app
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3307/studsluzba?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: matija
      SPRING_DATASOURCE_PASSWORD: Test123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  mysql_data:
