name: Deploy to GCP VM

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build and Deploy to VM
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set environment variable for version folder
      run: echo "RELEASE_FOLDER=studsluzba_${{ github.run_number }}" >> $GITHUB_ENV

    - name: Copy project to VM
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.GCP_VM_HOST }}
        username: ${{ secrets.GCP_VM_USER }}
        key: ${{ secrets.GCP_SSH_KEY }}
        source: "studsluzba"
        target: "~/deployments/${{ env.RELEASE_FOLDER }}"

    - name: Deploy via Docker Compose on VM
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.GCP_VM_HOST }}
        username: ${{ secrets.GCP_VM_USER }}
        key: ${{ secrets.GCP_SSH_KEY }}
        script: |
          cd ~/deployments/${{ env.RELEASE_FOLDER }}
          
          echo "Stopping previous containers (if running)..."
          docker-compose down || true
          
          echo "Starting new version from $RELEASE_FOLDER..."
          docker-compose up --build -d
          
          echo "Linking this version as 'latest'..."
          ln -sfn ~/deployments/${{ env.RELEASE_FOLDER }} ~/deployments/latest

          echo "Deployment finished: $RELEASE_FOLDER"
