name: Deploy to GCP VM

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build and Deploy to VM
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean package

    - name: Copy files to VM
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.GCP_VM_HOST }}
        username: ${{ secrets.GCP_VM_USER }}
        key: ${{ secrets.GCP_SSH_KEY }}
        source: "target/studsluzba_server-0.0.1-SNAPSHOT.jar"
        target: "~/studsluzba/target"

    - name: Restart application on VM
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.GCP_VM_HOST }}
        username: ${{ secrets.GCP_VM_USER }}
        key: ${{ secrets.GCP_SSH_KEY }}
        script: |
          cd ~/studsluzba
          docker-compose down
          docker-compose up --build -d
