name: Deploy to GCP VM

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build and Deploy to VM
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set environment variable for version folder
      run: echo "RELEASE_FOLDER=studsluzba_${{ github.run_number }}" >> $GITHUB_ENV

    - name: Build with Maven
      run: mvn clean package
      working-directory: studsluzba_server

    - name: Copy project to VM
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.GCP_VM_HOST }}
        username: ${{ secrets.GCP_VM_USER }}
        key: ${{ secrets.GCP_SSH_KEY }}
        source: "studsluzba_server"
        target: "~/deployments/${{ env.RELEASE_FOLDER }}"

    - name: Deploy via Docker Compose on VM
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.GCP_VM_HOST }}
        username: ${{ secrets.GCP_VM_USER }}
        key: ${{ secrets.GCP_SSH_KEY }}
        script: |
          cd ~/deployments/${{ env.RELEASE_FOLDER }}
          docker-compose down || true
          docker-compose up --build -d
          ln -sfn ~/deployments/${{ env.RELEASE_FOLDER }} ~/deployments/latest
